version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
     - 6000:6000
     #sync de données
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    # env_file:
    #   - .env